name=input("Enter the name")
branch=input("Enter the branch")
gender=input("Enter the gender")
college=input("Enter the college")
age=int(input("Enter the age"))
print(name)
print(branch)
print(gender)
print(college)
print(age)
