print("Enter run scored by each player ")
p1=int(input("Enter score of 1st player"))
p2=int(input("Enter score by 2nd player"))
p3=int(input("Enter score by 3rd player"))
print("strike rate")
print("player1"  ,(p1/60)*100)
print("player2"  ,(p2/60)*100)
print("player3"   ,(p3/60)*100)
print("Run scored if play more 60 balls")
print("player1"  ,p1*2)
print("player2"   ,p2*2)
print("player3"    ,p3*3)
print("max number of sixes")
print("player1"  ,p1//6)
print("player2"  ,p2//6)
print("player3"  ,p3//6)
